name: Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run tests
        run: go test ./...



  deploy:
    runs-on: ubuntu-latest
    needs: test  
    steps:
    - name: Install cloudflared
      run: |
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        sudo mv cloudflared /usr/local/bin
        sudo chmod +x /usr/local/bin/cloudflared

    - name: SSH into server and deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_RPI }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh -o ProxyCommand="cloudflared access ssh --hostname %h" \
              -o StrictHostKeyChecking=no \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
              "cd /opt/portfolioSite && git pull && sudo docker compose down && sudo docker compose up --build -d"